# Generated by Django 3.1.7 on 2021-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='default_snippet', max_length=255),
        ),
    ]
